// GENERATED by scripts/render-deck-slides.ps1 — do not edit by hand.
// Each entry points at a PNG exported from the deck the app actually
// generates, so the step 7 preview and the downloaded file are the
// same artifact. Keyed by deck map: one bank template per deal.

export interface DeckRenderSlide {
  n: number;
  src: string;
  title: string;
}

export const deckRenderSlidesByDeck: Record<string, DeckRenderSlide[]> = {
  "jpm": [
    {"n": 1, "src": "/deck/jpm/slide-01.png", "title": "JPM | Strategic Payables Return on Investment for Denton County Electric Cooperative"},
    {"n": 2, "src": "/deck/jpm/slide-02.png", "title": "J.P. Morgan Disclaimer"},
    {"n": 3, "src": "/deck/jpm/slide-03.png", "title": "Slide 3"},
    {"n": 4, "src": "/deck/jpm/slide-04.png", "title": "Things we\u2019ve heard"},
    {"n": 5, "src": "/deck/jpm/slide-05.png", "title": "Optimize your payment workflows with Strategic Payables"},
    {"n": 6, "src": "/deck/jpm/slide-06.png", "title": "Product Overview | Client and supplier benefits"},
    {"n": 7, "src": "/deck/jpm/slide-07.png", "title": "Unmatched security with Paymode\u2019s 300 defensive layers"},
    {"n": 8, "src": "/deck/jpm/slide-08.png", "title": "Slide 8"},
    {"n": 9, "src": "/deck/jpm/slide-09.png", "title": "Payment File Analysis & Conversion Metrics"},
    {"n": 10, "src": "/deck/jpm/slide-10.png", "title": "Your Future State with Strategic Payables"},
    {"n": 11, "src": "/deck/jpm/slide-11.png", "title": "Strategic Payables may Save You Money"},
    {"n": 12, "src": "/deck/jpm/slide-12.png", "title": "Slide 12"},
    {"n": 13, "src": "/deck/jpm/slide-13.png", "title": "Virtual Card Payments"},
    {"n": 14, "src": "/deck/jpm/slide-14.png", "title": "Premium Network Payments"},
    {"n": 15, "src": "/deck/jpm/slide-15.png", "title": "Basic Network Payments"},
    {"n": 16, "src": "/deck/jpm/slide-16.png", "title": "Outsourced Check Payments"},
    {"n": 17, "src": "/deck/jpm/slide-17.png", "title": "AP Automation: ROI Summary"},
    {"n": 18, "src": "/deck/jpm/slide-18.png", "title": "Slide 18"},
    {"n": 19, "src": "/deck/jpm/slide-19.png", "title": "Summary"},
    {"n": 20, "src": "/deck/jpm/slide-20.png", "title": "Slide 20"},
    {"n": 21, "src": "/deck/jpm/slide-21.png", "title": "AP Automation Cost Savings Detail Summary"},
  ],
  "illume": [
    {"n": 1, "src": "/deck/illume/slide-01.png", "title": "Return on Investment for Illume Ag"},
    {"n": 2, "src": "/deck/illume/slide-02.png", "title": "Paymode Will Save You Money This is with what you could earn and save with Paymode."},
    {"n": 3, "src": "/deck/illume/slide-03.png", "title": "Things We\u2019ve Heard:"},
    {"n": 4, "src": "/deck/illume/slide-04.png", "title": "The Details"},
    {"n": 5, "src": "/deck/illume/slide-05.png", "title": "Proven Methodology and Approach"},
    {"n": 6, "src": "/deck/illume/slide-06.png", "title": "Payment File Analysis & Conversion Metrics"},
    {"n": 7, "src": "/deck/illume/slide-07.png", "title": "Virtual Card Payments"},
    {"n": 8, "src": "/deck/illume/slide-08.png", "title": "Premium Payments"},
    {"n": 9, "src": "/deck/illume/slide-09.png", "title": "Basic Payments"},
    {"n": 10, "src": "/deck/illume/slide-10.png", "title": "ACH Program Migration"},
    {"n": 11, "src": "/deck/illume/slide-11.png", "title": "Outsourced Check Payments"},
    {"n": 12, "src": "/deck/illume/slide-12.png", "title": "B2C Payments"},
    {"n": 13, "src": "/deck/illume/slide-13.png", "title": "Client Success Mission Statement"},
    {"n": 14, "src": "/deck/illume/slide-14.png", "title": "Maximize Results with Speed & Security"},
    {"n": 15, "src": "/deck/illume/slide-15.png", "title": "Program Optimization Continuous Vendor Enablement"},
    {"n": 16, "src": "/deck/illume/slide-16.png", "title": "Dedicated to Maximizing Client Success"},
    {"n": 17, "src": "/deck/illume/slide-17.png", "title": "AP Automation: ROI Summary"},
    {"n": 18, "src": "/deck/illume/slide-18.png", "title": "Appendix AP Automation:  Cost Savings Summary"},
    {"n": 19, "src": "/deck/illume/slide-19.png", "title": "AP Automation Cost Savings Detail Summary"},
  ],
};

/** Slides for a deck map, or [] for deals that never produced a deck. */
export function deckSlidesFor(deckMap: string | undefined): DeckRenderSlide[] {
  if (!deckMap) return [];
  return deckRenderSlidesByDeck[deckMap] ?? [];
}
