// GENERATED by POC Deals/_dump/build_file8_workbook.py — do not hand-edit.
// Real tabs, real formulas and real calculated values from the value
// statement this app builds (engine/steps/build_workbooks.ps1).

export interface SheetCell {
  /** Calculated value, already formatted. */
  v: string;
  /** The real Excel formula, when the cell is calculated rather than pasted. */
  f?: string;
}

export interface SheetTab {
  name: string;
  startRow: number;
  startCol: number;
  headerRows: number;
  /** True for the tab the reviewed vendor rows are pasted into. */
  input: boolean;
  rows: SheetCell[][];
}

export const valueStatementTabs: SheetTab[] = [
 {
  "name": "VHF",
  "startRow": 2,
  "startCol": 1,
  "headerRows": 1,
  "input": true,
  "rows": [
   [
    {
     "v": "Potential ROC ID"
    },
    {
     "v": "Vendor Number"
    },
    {
     "v": "Vendor Name"
    },
    {
     "v": "Country"
    },
    {
     "v": "Payment Types"
    },
    {
     "v": "Invoices"
    },
    {
     "v": "Transactions"
    },
    {
     "v": "Spend"
    }
   ],
   [
    {
     "v": "1540774"
    },
    {
     "v": "BT 396^1348"
    },
    {
     "v": "SHELL ENERGY NORTH AMERICA (US) LP"
    },
    {
     "v": "USA"
    },
    {
     "v": "Wire"
    },
    {
     "v": ""
    },
    {
     "v": "37"
    },
    {
     "v": "233,539,062"
    }
   ],
   [
    {
     "v": "389324"
    },
    {
     "v": "BT 168^100524"
    },
    {
     "v": "ERCOT"
    },
    {
     "v": "USA"
    },
    {
     "v": "Wire"
    },
    {
     "v": ""
    },
    {
     "v": "223"
    },
    {
     "v": "86,364,403.49"
    }
   ],
   [
    {
     "v": "93569"
    },
    {
     "v": "BT 249^103783"
    },
    {
     "v": "STUART C IRBY CO"
    },
    {
     "v": "USA"
    },
    {
     "v": "ACH"
    },
    {
     "v": ""
    },
    {
     "v": "101"
    },
    {
     "v": "81,668,547.35"
    }
   ],
   [
    {
     "v": "120312"
    },
    {
     "v": "BT 128^100401"
    },
    {
     "v": "ATMOS PIPELINE - TEXAS"
    },
    {
     "v": "USA"
    },
    {
     "v": "Wire"
    },
    {
     "v": ""
    },
    {
     "v": "12"
    },
    {
     "v": "45,202,928.24"
    }
   ],
   [
    {
     "v": "271795301"
    },
    {
     "v": "BT 143^100454"
    },
    {
     "v": "CONOCOPHILLIPS COMPANY"
    },
    {
     "v": "USA"
    },
    {
     "v": "Wire"
    },
    {
     "v": ""
    },
    {
     "v": "22"
    },
    {
     "v": "38,568,460.70"
    }
   ],
   [
    {
     "v": "276045"
    },
    {
     "v": "BT 115^100355"
    },
    {
     "v": "TEXAS COMPTROLLER OF PUBLIC ACCOUNTS"
    },
    {
     "v": "USA"
    },
    {
     "v": "Wire"
    },
    {
     "v": ""
    },
    {
     "v": "30"
    },
    {
     "v": "28,447,050.22"
    }
   ],
   [
    {
     "v": "3082046"
    },
    {
     "v": "BT 588^1697"
    },
    {
     "v": "PRIMORIS DISTRIBUTION SERVICES, INC"
    },
    {
     "v": "USA"
    },
    {
     "v": "ACH"
    },
    {
     "v": ""
    },
    {
     "v": "110"
    },
    {
     "v": "23,509,943.31"
    }
   ],
   [
    {
     "v": "271795580"
    },
    {
     "v": "BT 422^1395"
    },
    {
     "v": "STONEX FINANCIAL INC"
    },
    {
     "v": "USA"
    },
    {
     "v": "Wire"
    },
    {
     "v": ""
    },
    {
     "v": "22"
    },
    {
     "v": "22,836,650"
    }
   ],
   [
    {
     "v": "6040432"
    },
    {
     "v": "BT 140^100447"
    },
    {
     "v": "COBANK"
    },
    {
     "v": "USA"
    },
    {
     "v": "Check"
    },
    {
     "v": ""
    },
    {
     "v": "45"
    },
    {
     "v": "16,933,510.18"
    }
   ],
   [
    {
     "v": "271795206"
    },
    {
     "v": "BT 48^100148"
    },
    {
     "v": "UNITED STATES TREASURY"
    },
    {
     "v": "USA"
    },
    {
     "v": "Wire"
    },
    {
     "v": ""
    },
    {
     "v": "71"
    },
    {
     "v": "11,630,372.25"
    }
   ],
   [
    {
     "v": "2028833"
    },
    {
     "v": "BT 391^130735"
    },
    {
     "v": "TEXAS STATE UTILITIES INC"
    },
    {
     "v": "USA"
    },
    {
     "v": "Check"
    },
    {
     "v": ""
    },
    {
     "v": "80"
    },
    {
     "v": "11,122,365.94"
    }
   ],
   [
    {
     "v": "4284700"
    },
    {
     "v": "BT 491^150099"
    },
    {
     "v": "PCI UTILITIES LLC"
    },
    {
     "v": "USA"
    },
    {
     "v": "Check"
    },
    {
     "v": ""
    },
    {
     "v": "71"
    },
    {
     "v": "10,498,329.14"
    }
   ],
   [
    {
     "v": "271795411"
    },
    {
     "v": "BT 253^104053"
    },
    {
     "v": "CALIBER CONSTRUCTION INC"
    },
    {
     "v": "USA"
    },
    {
     "v": "ACH"
    },
    {
     "v": ""
    },
    {
     "v": "16"
    },
    {
     "v": "8,955,952.34"
    }
   ],
   [
    {
     "v": "271795621"
    },
    {
     "v": "BT 463^146084"
    },
    {
     "v": "ENLINK GAS MARKETING, LP"
    },
    {
     "v": "USA"
    },
    {
     "v": "Wire"
    },
    {
     "v": ""
    },
    {
     "v": "12"
    },
    {
     "v": "8,900,800"
    }
   ],
   [
    {
     "v": "2675837"
    },
    {
     "v": "BT 404^136295"
    },
    {
     "v": "STANDARD UTILITY CONSTRUCTION INC"
    },
    {
     "v": "USA"
    },
    {
     "v": "Check"
    },
    {
     "v": ""
    },
    {
     "v": "77"
    },
    {
     "v": "8,871,648.26"
    }
   ],
   [
    {
     "v": "608271"
    },
    {
     "v": "BT 9^100015"
    },
    {
     "v": "FRISCO, CITY OF"
    },
    {
     "v": "USA"
    },
    {
     "v": "ACH"
    },
    {
     "v": ""
    },
    {
     "v": "1"
    },
    {
     "v": "7,645,223.43"
    }
   ],
   [
    {
     "v": "188004"
    },
    {
     "v": "BT 113^100339"
    },
    {
     "v": "SIRIUS COMPUTER SOLUTIONS INC"
    },
    {
     "v": "USA"
    },
    {
     "v": "ACH"
    },
    {
     "v": ""
    },
    {
     "v": "41"
    },
    {
     "v": "6,506,454.17"
    }
   ],
   [
    {
     "v": "1773885"
    },
    {
     "v": "BT 458^145140"
    },
    {
     "v": "DCG CONSTRUCTION LLC"
    },
    {
     "v": "USA"
    },
    {
     "v": "Check"
    },
    {
     "v": ""
    },
    {
     "v": "46"
    },
    {
     "v": "5,528,325.48"
    }
   ],
   [
    {
     "v": "271795571"
    },
    {
     "v": "BT 413^138146"
    },
    {
     "v": "ASPS HOLDINGS LLC"
    },
    {
     "v": "USA"
    },
    {
     "v": "Check"
    },
    {
     "v": ""
    },
    {
     "v": "34"
    },
    {
     "v": "4,814,356.19"
    }
   ],
   [
    {
     "v": "271795240"
    },
    {
     "v": "BT 82^100255"
    },
    {
     "v": "NATIONAL RURAL ELECTRIC COOPERATIVE ASSO"
    },
    {
     "v": "USA"
    },
    {
     "v": "Check"
    },
    {
     "v": ""
    },
    {
     "v": "78"
    },
    {
     "v": "4,766,724.28"
    }
   ],
   [
    {
     "v": "453333"
    },
    {
     "v": "BT 159^100500"
    },
    {
     "v": "DENTON COUNTY TAX ASSESSOR/COLLECTOR"
    },
    {
     "v": "USA"
    },
    {
     "v": "Check"
    },
    {
     "v": ""
    },
    {
     "v": "14"
    },
    {
     "v": "4,625,121.33"
    }
   ],
   [
    {
     "v": "579896"
    },
    {
     "v": "BT 270^106488"
    },
    {
     "v": "USIC LOCATING SERVICES INC"
    },
    {
     "v": "USA"
    },
    {
     "v": "Check"
    },
    {
     "v": ""
    },
    {
     "v": "24"
    },
    {
     "v": "4,483,998.62"
    }
   ],
   [
    {
     "v": "271795369"
    },
    {
     "v": "BT 211^100665"
    },
    {
     "v": "MCKINNEY, CITY OF"
    },
    {
     "v": "USA"
    },
    {
     "v": "ACH"
    },
    {
     "v": ""
    },
    {
     "v": "4"
    },
    {
     "v": "3,810,899.29"
    }
   ],
   [
    {
     "v": "807317"
    },
    {
     "v": "BT 543^161430"
    },
    {
     "v": "DRIVER PIPELINE COMPANY, INC"
    },
    {
     "v": "USA"
    },
    {
     "v": "Check"
    },
    {
     "v": ""
    },
    {
     "v": "21"
    },
    {
     "v": "3,717,247.13"
    }
   ],
   [
    {
     "v": "196136"
    },
    {
     "v": "BT 2^100005"
    },
    {
     "v": "FLOWER MOUND, CITY OF"
    },
    {
     "v": "USA"
    },
    {
     "v": "ACH"
    },
    {
     "v": ""
    },
    {
     "v": "5"
    },
    {
     "v": "3,449,120.94"
    }
   ],
   [
    {
     "v": "1714856"
    },
    {
     "v": "BT 57^100190"
    },
    {
     "v": "COLLIN COUNTY TAX A/C"
    },
    {
     "v": "USA"
    },
    {
     "v": "Check"
    },
    {
     "v": ""
    },
    {
     "v": "1"
    },
    {
     "v": "2,664,490.14"
    }
   ],
   [
    {
     "v": "271795197"
    },
    {
     "v": "BT 39^100125"
    },
    {
     "v": "GUY WILLIS INSPECTION CO"
    },
    {
     "v": "USA"
    },
    {
     "v": "Check"
    },
    {
     "v": ""
    },
    {
     "v": "58"
    },
    {
     "v": "2,607,180"
    }
   ],
   [
    {
     "v": "1381878"
    },
    {
     "v": "BT 207^100652"
    },
    {
     "v": "LITTLE ELM, CITY OF"
    },
    {
     "v": "USA"
    },
    {
     "v": "Check"
    },
    {
     "v": ""
    },
    {
     "v": "5"
    },
    {
     "v": "2,548,927.09"
    }
   ],
   [
    {
     "v": "608271"
    },
    {
     "v": "BT 10^100015"
    },
    {
     "v": "FRISCO, CITY OF"
    },
    {
     "v": "USA"
    },
    {
     "v": "Check"
    },
    {
     "v": ""
    },
    {
     "v": "14"
    },
    {
     "v": "1,658,075.60"
    }
   ],
   [
    {
     "v": "3525550"
    },
    {
     "v": "BT 567^166842"
    },
    {
     "v": "MISSION SITE SERVICES LLC"
    },
    {
     "v": "USA"
    },
    {
     "v": "ACH"
    },
    {
     "v": ""
    },
    {
     "v": "44"
    },
    {
     "v": "1,657,720.97"
    }
   ],
   [
    {
     "v": "209644"
    },
    {
     "v": "BT 24^100056"
    },
    {
     "v": "TEXAS METER AND DEVICE CO"
    },
    {
     "v": "USA"
    },
    {
     "v": "Check"
    },
    {
     "v": ""
    },
    {
     "v": "33"
    },
    {
     "v": "1,560,621.30"
    }
   ],
   [
    {
     "v": "271795528"
    },
    {
     "v": "BT 370^125347"
    },
    {
     "v": "WM-RENEWABLE ENERGY LLC"
    },
    {
     "v": "USA"
    },
    {
     "v": "ACH"
    },
    {
     "v": ""
    },
    {
     "v": "12"
    },
    {
     "v": "1,555,585.46"
    }
   ]
  ]
 },
 {
  "name": "Calculations",
  "startRow": 3,
  "startCol": 4,
  "headerRows": 2,
  "input": false,
  "rows": [
   [
    {
     "v": ""
    },
    {
     "v": "Spend"
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": "Transactions"
    },
    {
     "v": ""
    },
    {
     "v": ""
    }
   ],
   [
    {
     "v": ""
    },
    {
     "v": "Check"
    },
    {
     "v": "ACH"
    },
    {
     "v": "PMX Classic"
    },
    {
     "v": "Wire"
    },
    {
     "v": "Card"
    },
    {
     "v": "Total"
    },
    {
     "v": "Check"
    },
    {
     "v": "ACH"
    },
    {
     "v": "PMX Classic"
    }
   ],
   [
    {
     "v": "Total File"
    },
    {
     "v": "128,642,053.72",
     "f": "=SUMIF(VHF!$AK:$AK,Calculations!E$4,VHF!$H:$H)"
    },
    {
     "v": "155,785,615.42",
     "f": "=SUMIF(VHF!$AK:$AK,Calculations!F$4,VHF!$H:$H)"
    },
    {
     "v": "0",
     "f": "=SUMIF(VHF!$AK:$AK,Calculations!G$4,VHF!$H:$H)"
    },
    {
     "v": "476,904,015.35",
     "f": "=SUMIF(VHF!$AK:$AK,Calculations!H$4,VHF!$H:$H)"
    },
    {
     "v": "0",
     "f": "=SUMIF(VHF!$AK:$AK,Calculations!I$4,VHF!$H:$H)"
    },
    {
     "v": "761,331,684.49",
     "f": "=SUM(E5:I5)"
    },
    {
     "v": "4,436",
     "f": "=SUMIF(VHF!$AK:$AK,Calculations!K$4,VHF!$G:$G)"
    },
    {
     "v": "1,065",
     "f": "=SUMIF(VHF!$AK:$AK,Calculations!L$4,VHF!$G:$G)"
    },
    {
     "v": "0",
     "f": "=SUMIF(VHF!$AK:$AK,Calculations!M$4,VHF!$G:$G)"
    }
   ],
   [
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    }
   ],
   [
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    }
   ],
   [
    {
     "v": ""
    },
    {
     "v": "Spend"
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": "Transactions"
    },
    {
     "v": ""
    },
    {
     "v": ""
    }
   ],
   [
    {
     "v": "Card Program Campaigning"
    },
    {
     "v": "Check"
    },
    {
     "v": "ACH"
    },
    {
     "v": "PMX Classic"
    },
    {
     "v": "Wire"
    },
    {
     "v": "Card"
    },
    {
     "v": "Total"
    },
    {
     "v": "Check"
    },
    {
     "v": "ACH"
    },
    {
     "v": "PMX Classic"
    }
   ],
   [
    {
     "v": "Campaigning"
    },
    {
     "v": "13,719,487.58",
     "f": "=SUM(E11:E20)"
    },
    {
     "v": "8,595,034.02",
     "f": "=SUM(F11:F20)"
    },
    {
     "v": "0",
     "f": "=SUM(G11:G20)"
    },
    {
     "v": "0",
     "f": "=SUM(H11:H20)"
    },
    {
     "v": "0",
     "f": "=SUM(I11:I20)"
    },
    {
     "v": "22,314,521.60",
     "f": "=SUM(J11:J20)"
    },
    {
     "v": "1,154",
     "f": "=SUM(K11:K20)"
    },
    {
     "v": "409",
     "f": "=SUM(L11:L20)"
    },
    {
     "v": "0",
     "f": "=SUM(M11:M20)"
    }
   ],
   [
    {
     "v": "Virtual Card Migration"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D11,VHF!$AK:$AK,Calculations!E$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D11,VHF!$AK:$AK,Calculations!F$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D11,VHF!$AK:$AK,Calculations!G$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D11,VHF!$AK:$AK,Calculations!H$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D11,VHF!$AK:$AK,Calculations!I$9)"
    },
    {
     "v": "0",
     "f": "=SUM(E11:I11)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D11,VHF!$AK:$AK,Calculations!K$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D11,VHF!$AK:$AK,Calculations!L$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D11,VHF!$AK:$AK,Calculations!M$9)"
    }
   ],
   [
    {
     "v": "Card Network Open Acceptor"
    },
    {
     "v": "3,801,247.62",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D12,VHF!$AK:$AK,Calculations!E$9)"
    },
    {
     "v": "29,070.96",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D12,VHF!$AK:$AK,Calculations!F$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D12,VHF!$AK:$AK,Calculations!G$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D12,VHF!$AK:$AK,Calculations!H$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D12,VHF!$AK:$AK,Calculations!I$9)"
    },
    {
     "v": "3,830,318.58",
     "f": "=SUM(E12:I12)"
    },
    {
     "v": "453",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D12,VHF!$AK:$AK,Calculations!K$9)"
    },
    {
     "v": "66",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D12,VHF!$AK:$AK,Calculations!L$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D12,VHF!$AK:$AK,Calculations!M$9)"
    }
   ],
   [
    {
     "v": "ESN Open Acceptor"
    },
    {
     "v": "49,516.32",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D13,VHF!$AK:$AK,Calculations!E$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D13,VHF!$AK:$AK,Calculations!F$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D13,VHF!$AK:$AK,Calculations!G$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D13,VHF!$AK:$AK,Calculations!H$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D13,VHF!$AK:$AK,Calculations!I$9)"
    },
    {
     "v": "49,516.32",
     "f": "=SUM(E13:I13)"
    },
    {
     "v": "12",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D13,VHF!$AK:$AK,Calculations!K$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D13,VHF!$AK:$AK,Calculations!L$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D13,VHF!$AK:$AK,Calculations!M$9)"
    }
   ],
   [
    {
     "v": "Card Network Selective Acceptor"
    },
    {
     "v": "90,249.73",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D14,VHF!$AK:$AK,Calculations!E$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D14,VHF!$AK:$AK,Calculations!F$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D14,VHF!$AK:$AK,Calculations!G$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D14,VHF!$AK:$AK,Calculations!H$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D14,VHF!$AK:$AK,Calculations!I$9)"
    },
    {
     "v": "90,249.73",
     "f": "=SUM(E14:I14)"
    },
    {
     "v": "35",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D14,VHF!$AK:$AK,Calculations!K$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D14,VHF!$AK:$AK,Calculations!L$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D14,VHF!$AK:$AK,Calculations!M$9)"
    }
   ],
   [
    {
     "v": "ESN Selective Acceptor"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D15,VHF!$AK:$AK,Calculations!E$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D15,VHF!$AK:$AK,Calculations!F$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D15,VHF!$AK:$AK,Calculations!G$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D15,VHF!$AK:$AK,Calculations!H$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D15,VHF!$AK:$AK,Calculations!I$9)"
    },
    {
     "v": "0",
     "f": "=SUM(E15:I15)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D15,VHF!$AK:$AK,Calculations!K$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D15,VHF!$AK:$AK,Calculations!L$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D15,VHF!$AK:$AK,Calculations!M$9)"
    }
   ],
   [
    {
     "v": "High Potential Card"
    },
    {
     "v": "2,209,332.76",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D16,VHF!$AK:$AK,Calculations!E$9)"
    },
    {
     "v": "1,156,785.13",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D16,VHF!$AK:$AK,Calculations!F$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D16,VHF!$AK:$AK,Calculations!G$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D16,VHF!$AK:$AK,Calculations!H$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D16,VHF!$AK:$AK,Calculations!I$9)"
    },
    {
     "v": "3,366,117.89",
     "f": "=SUM(E16:I16)"
    },
    {
     "v": "269",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D16,VHF!$AK:$AK,Calculations!K$9)"
    },
    {
     "v": "44",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D16,VHF!$AK:$AK,Calculations!L$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D16,VHF!$AK:$AK,Calculations!M$9)"
    }
   ],
   [
    {
     "v": "Low Potential Card"
    },
    {
     "v": "7,569,141.15",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D17,VHF!$AK:$AK,Calculations!E$9)"
    },
    {
     "v": "7,409,177.93",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D17,VHF!$AK:$AK,Calculations!F$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D17,VHF!$AK:$AK,Calculations!G$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D17,VHF!$AK:$AK,Calculations!H$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D17,VHF!$AK:$AK,Calculations!I$9)"
    },
    {
     "v": "14,978,319.08",
     "f": "=SUM(E17:I17)"
    },
    {
     "v": "385",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D17,VHF!$AK:$AK,Calculations!K$9)"
    },
    {
     "v": "299",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D17,VHF!$AK:$AK,Calculations!L$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D17,VHF!$AK:$AK,Calculations!M$9)"
    }
   ],
   [
    {
     "v": "Above Threshold Card (>$5MM)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D18,VHF!$AK:$AK,Calculations!E$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D18,VHF!$AK:$AK,Calculations!F$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D18,VHF!$AK:$AK,Calculations!G$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D18,VHF!$AK:$AK,Calculations!H$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D18,VHF!$AK:$AK,Calculations!I$9)"
    },
    {
     "v": "0",
     "f": "=SUM(E18:I18)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D18,VHF!$AK:$AK,Calculations!K$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D18,VHF!$AK:$AK,Calculations!L$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D18,VHF!$AK:$AK,Calculations!M$9)"
    }
   ],
   [
    {
     "v": "Above Threshold Card (>$5MM) Booking Calc"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D19,VHF!$AK:$AK,Calculations!E$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D19,VHF!$AK:$AK,Calculations!F$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D19,VHF!$AK:$AK,Calculations!G$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D19,VHF!$AK:$AK,Calculations!H$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D19,VHF!$AK:$AK,Calculations!I$9)"
    },
    {
     "v": "0",
     "f": "=SUM(E19:I19)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D19,VHF!$AK:$AK,Calculations!K$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D19,VHF!$AK:$AK,Calculations!L$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D19,VHF!$AK:$AK,Calculations!M$9)"
    }
   ],
   [
    {
     "v": "Card Upside"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D20,VHF!$AK:$AK,Calculations!E$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D20,VHF!$AK:$AK,Calculations!F$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D20,VHF!$AK:$AK,Calculations!G$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D20,VHF!$AK:$AK,Calculations!H$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D20,VHF!$AK:$AK,Calculations!I$9)"
    },
    {
     "v": "0",
     "f": "=SUM(E20:I20)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D20,VHF!$AK:$AK,Calculations!K$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D20,VHF!$AK:$AK,Calculations!L$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D20,VHF!$AK:$AK,Calculations!M$9)"
    }
   ],
   [
    {
     "v": "Exclusions"
    },
    {
     "v": "114,922,566.14",
     "f": "=SUM(E22:E24)"
    },
    {
     "v": "147,190,581.40",
     "f": "=SUM(F22:F24)"
    },
    {
     "v": "0",
     "f": "=SUM(G22:G24)"
    },
    {
     "v": "476,904,015.35",
     "f": "=SUM(H22:H24)"
    },
    {
     "v": "0",
     "f": "=SUM(I22:I24)"
    },
    {
     "v": "739,017,162.89",
     "f": "=SUM(J22:J24)"
    },
    {
     "v": "3,282",
     "f": "=SUM(K22:K24)"
    },
    {
     "v": "656",
     "f": "=SUM(L22:L24)"
    },
    {
     "v": "0",
     "f": "=SUM(M22:M24)"
    }
   ],
   [
    {
     "v": "Non-Match"
    },
    {
     "v": "83,929,987.91",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D22,VHF!$AK:$AK,Calculations!E$9)"
    },
    {
     "v": "130,838,993.55",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D22,VHF!$AK:$AK,Calculations!F$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D22,VHF!$AK:$AK,Calculations!G$9)"
    },
    {
     "v": "442,434,819.10",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D22,VHF!$AK:$AK,Calculations!H$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D22,VHF!$AK:$AK,Calculations!I$9)"
    },
    {
     "v": "657,203,800.56",
     "f": "=SUM(E22:I22)"
    },
    {
     "v": "2,771",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D22,VHF!$AK:$AK,Calculations!K$9)"
    },
    {
     "v": "575",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D22,VHF!$AK:$AK,Calculations!L$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D22,VHF!$AK:$AK,Calculations!M$9)"
    }
   ],
   [
    {
     "v": "Non-Target"
    },
    {
     "v": "30,992,578.23",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D23,VHF!$AK:$AK,Calculations!E$9)"
    },
    {
     "v": "16,351,587.85",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D23,VHF!$AK:$AK,Calculations!F$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D23,VHF!$AK:$AK,Calculations!G$9)"
    },
    {
     "v": "34,469,196.25",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D23,VHF!$AK:$AK,Calculations!H$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D23,VHF!$AK:$AK,Calculations!I$9)"
    },
    {
     "v": "81,813,362.33",
     "f": "=SUM(E23:I23)"
    },
    {
     "v": "511",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D23,VHF!$AK:$AK,Calculations!K$9)"
    },
    {
     "v": "81",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D23,VHF!$AK:$AK,Calculations!L$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D23,VHF!$AK:$AK,Calculations!M$9)"
    }
   ],
   [
    {
     "v": "No Payment Data"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D24,VHF!$AK:$AK,Calculations!E$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D24,VHF!$AK:$AK,Calculations!F$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D24,VHF!$AK:$AK,Calculations!G$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D24,VHF!$AK:$AK,Calculations!H$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AU:$AU,$D24,VHF!$AK:$AK,Calculations!I$9)"
    },
    {
     "v": "0",
     "f": "=SUM(E24:I24)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D24,VHF!$AK:$AK,Calculations!K$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D24,VHF!$AK:$AK,Calculations!L$9)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AU:$AU,$D24,VHF!$AK:$AK,Calculations!M$9)"
    }
   ],
   [
    {
     "v": "Card Program Projection"
    },
    {
     "v": "5,870,806.43",
     "f": "=SUM(E26:E38)"
    },
    {
     "v": "515,208.37",
     "f": "=SUM(F26:F38)"
    },
    {
     "v": "0",
     "f": "=SUM(G26:G38)"
    },
    {
     "v": "0",
     "f": "=SUM(H26:H38)"
    },
    {
     "v": "0",
     "f": "=SUM(I26:I38)"
    },
    {
     "v": "6,386,014.80",
     "f": "=SUM(J26:J38)"
    },
    {
     "v": "642.47",
     "f": "=SUM(K26:K38)"
    },
    {
     "v": "85.35",
     "f": "=SUM(L26:L38)"
    },
    {
     "v": "0",
     "f": "=SUM(M26:M38)"
    }
   ]
  ]
 },
 {
  "name": "JPM Data Converted (Paymode VC)",
  "startRow": 2,
  "startCol": 1,
  "headerRows": 1,
  "input": false,
  "rows": [
   [
    {
     "v": ""
    },
    {
     "v": "Total"
    },
    {
     "v": "Check"
    },
    {
     "v": "ACH"
    },
    {
     "v": "PMX Classic ACH"
    },
    {
     "v": "Card"
    },
    {
     "v": "Wire"
    }
   ],
   [
    {
     "v": "Total Vendors in Original File"
    },
    {
     "v": "625",
     "f": "=Calculations!V5"
    },
    {
     "v": "549",
     "f": "=Calculations!Q5"
    },
    {
     "v": "64",
     "f": "=Calculations!R5"
    },
    {
     "v": "0",
     "f": "=Calculations!S5"
    },
    {
     "v": "0",
     "f": "=Calculations!U5"
    },
    {
     "v": "12",
     "f": "=Calculations!T5"
    }
   ],
   [
    {
     "v": "Total Transactions in Original File"
    },
    {
     "v": "5,981",
     "f": "=Calculations!P5"
    },
    {
     "v": "4,436",
     "f": "=Calculations!K5"
    },
    {
     "v": "1,065",
     "f": "=Calculations!L5"
    },
    {
     "v": "0",
     "f": "=Calculations!M5"
    },
    {
     "v": "0",
     "f": "=Calculations!O5"
    },
    {
     "v": "480",
     "f": "=Calculations!N5"
    }
   ],
   [
    {
     "v": "Total Spend in Original File"
    },
    {
     "v": "761,331,684.49",
     "f": "=Calculations!J5"
    },
    {
     "v": "128,642,053.72",
     "f": "=Calculations!E5"
    },
    {
     "v": "155,785,615.42",
     "f": "=Calculations!F5"
    },
    {
     "v": "0",
     "f": "=Calculations!G5"
    },
    {
     "v": "0",
     "f": "=Calculations!I5"
    },
    {
     "v": "476,904,015.35",
     "f": "=Calculations!H5"
    }
   ],
   [
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    }
   ],
   [
    {
     "v": "Campaign Targets - Vendors"
    },
    {
     "v": "481",
     "f": "=Calculations!V10+Calculations!V43+Calculations!V95+Calculations!V139+Calculations!V157"
    },
    {
     "v": "423",
     "f": "=Calculations!Q10+Calculations!Q43+Calculations!Q95+Calculations!Q139+Calculations!Q157"
    },
    {
     "v": "49",
     "f": "=Calculations!R10+Calculations!R43+Calculations!R95+Calculations!R139+Calculations!R157"
    },
    {
     "v": "0",
     "f": "=Calculations!S10+Calculations!S43+Calculations!S95+Calculations!S139+Calculations!S157"
    },
    {
     "v": "0",
     "f": "=Calculations!U10+Calculations!U43+Calculations!U95+Calculations!U139+Calculations!U157"
    },
    {
     "v": "9",
     "f": "=Calculations!T10+Calculations!T43+Calculations!T95+Calculations!T139+Calculations!T157"
    }
   ],
   [
    {
     "v": "Campaign Targets - Transactions"
    },
    {
     "v": "5,210",
     "f": "=Calculations!P10+Calculations!P43+Calculations!P95+Calculations!P139+Calculations!P157"
    },
    {
     "v": "3,840",
     "f": "=Calculations!K10+Calculations!K43+Calculations!K95+Calculations!K139+Calculations!K157"
    },
    {
     "v": "984",
     "f": "=Calculations!L10+Calculations!L43+Calculations!L95+Calculations!L139+Calculations!L157"
    },
    {
     "v": "0",
     "f": "=Calculations!M10+Calculations!M43+Calculations!M95+Calculations!M139+Calculations!M157"
    },
    {
     "v": "0",
     "f": "=Calculations!O10+Calculations!O43+Calculations!O95+Calculations!O139+Calculations!O157"
    },
    {
     "v": "386",
     "f": "=Calculations!N10+Calculations!N43+Calculations!N95+Calculations!N139+Calculations!N157"
    }
   ],
   [
    {
     "v": "Campaign Targets - Spend"
    },
    {
     "v": "674,330,821.74",
     "f": "=Calculations!J10+Calculations!J43+Calculations!J95+Calculations!J139+Calculations!J157"
    },
    {
     "v": "92,461,975.07",
     "f": "=Calculations!E10+Calculations!E43+Calculations!E95+Calculations!E139+Calculations!E157"
    },
    {
     "v": "139,434,027.57",
     "f": "=Calculations!F10+Calculations!F43+Calculations!F95+Calculations!F139+Calculations!F157"
    },
    {
     "v": "0",
     "f": "=Calculations!G10+Calculations!G43+Calculations!G95+Calculations!G139+Calculations!G157"
    },
    {
     "v": "0",
     "f": "=Calculations!I10+Calculations!I43+Calculations!I95+Calculations!I139+Calculations!I157"
    },
    {
     "v": "442,434,819.10",
     "f": "=Calculations!H10+Calculations!H43+Calculations!H95+Calculations!H139+Calculations!H157"
    }
   ],
   [
    {
     "v": "Strategic Vendor - Vendors"
    },
    {
     "v": "80",
     "f": "=SUM(C10:G10)"
    },
    {
     "v": "66",
     "f": "=COUNTIFS(VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"<>Non-Target\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!C$2)"
    },
    {
     "v": "13",
     "f": "=COUNTIFS(VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"<>Non-Target\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!D$2)"
    },
    {
     "v": "0",
     "f": "=COUNTIFS(VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"<>Non-Target\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!E$2)"
    },
    {
     "v": "0",
     "f": "=COUNTIFS(VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"<>Non-Target\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!F$2)"
    },
    {
     "v": "1",
     "f": "=COUNTIFS(VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"<>Non-Target\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!G$2)"
    }
   ],
   [
    {
     "v": "Strategic Vendor - Transactions"
    },
    {
     "v": "1,285",
     "f": "=SUM(C11:G11)"
    },
    {
     "v": "847",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"<>Non-Target\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!C$2)"
    },
    {
     "v": "408",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"<>Non-Target\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!D$2)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"<>Non-Target\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!E$2)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"<>Non-Target\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!F$2)"
    },
    {
     "v": "30",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"<>Non-Target\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!G$2)"
    }
   ],
   [
    {
     "v": "Strategic Vendor - Spend"
    },
    {
     "v": "166,192,329.48",
     "f": "=SUM(C12:G12)"
    },
    {
     "v": "24,611,761.10",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"<>Non-Target\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!C$2)"
    },
    {
     "v": "113,133,518.16",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"<>Non-Target\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!D$2)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"<>Non-Target\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!E$2)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"<>Non-Target\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!F$2)"
    },
    {
     "v": "28,447,050.22",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"<>Non-Target\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!G$2)"
    }
   ],
   [
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    }
   ],
   [
    {
     "v": "Network Matches - Vendors"
    },
    {
     "v": "170",
     "f": "=Calculations!V219"
    },
    {
     "v": "146",
     "f": "=Calculations!Q219"
    },
    {
     "v": "21",
     "f": "=Calculations!R219"
    },
    {
     "v": "0",
     "f": "=Calculations!S219"
    },
    {
     "v": "0",
     "f": "=Calculations!U219"
    },
    {
     "v": "3",
     "f": "=Calculations!T219"
    }
   ],
   [
    {
     "v": "Network Matches - Transactions"
    },
    {
     "v": "2,080",
     "f": "=Calculations!P219"
    },
    {
     "v": "1,534",
     "f": "=Calculations!K219"
    },
    {
     "v": "473",
     "f": "=Calculations!L219"
    },
    {
     "v": "0",
     "f": "=Calculations!M219"
    },
    {
     "v": "0",
     "f": "=Calculations!O219"
    },
    {
     "v": "73",
     "f": "=Calculations!N219"
    }
   ],
   [
    {
     "v": "Network Matches - Spend"
    },
    {
     "v": "322,120,877.71",
     "f": "=Calculations!J219"
    },
    {
     "v": "28,502,651.88",
     "f": "=Calculations!E219"
    },
    {
     "v": "13,474,948.06",
     "f": "=Calculations!F219"
    },
    {
     "v": "0",
     "f": "=Calculations!G219"
    },
    {
     "v": "0",
     "f": "=Calculations!I219"
    },
    {
     "v": "280,143,277.77",
     "f": "=Calculations!H219"
    }
   ],
   [
    {
     "v": "Strategic Vendor - Vendors"
    },
    {
     "v": "38",
     "f": "=SUM(C17:G17)"
    },
    {
     "v": "31",
     "f": "=COUNTIFS(VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"Match\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!C$2)"
    },
    {
     "v": "7",
     "f": "=COUNTIFS(VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"Match\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!D$2)"
    },
    {
     "v": "0",
     "f": "=COUNTIFS(VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"Match\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!E$2)"
    },
    {
     "v": "0",
     "f": "=COUNTIFS(VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"Match\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!F$2)"
    },
    {
     "v": "0",
     "f": "=COUNTIFS(VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"Match\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!G$2)"
    }
   ],
   [
    {
     "v": "Strategic Vendor - Transactions"
    },
    {
     "v": "537",
     "f": "=SUM(C18:G18)"
    },
    {
     "v": "364",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"Match\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!C$2)"
    },
    {
     "v": "173",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"Match\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!D$2)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"Match\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!E$2)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"Match\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!F$2)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$G:$G,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"Match\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!G$2)"
    }
   ],
   [
    {
     "v": "Strategic Vendor - Spend"
    },
    {
     "v": "14,202,206.51",
     "f": "=SUM(C19:G19)"
    },
    {
     "v": "7,197,187.78",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"Match\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!C$2)"
    },
    {
     "v": "7,005,018.73",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"Match\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!D$2)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"Match\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!E$2)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"Match\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!F$2)"
    },
    {
     "v": "0",
     "f": "=SUMIFS(VHF!$H:$H,VHF!$AQ:$AQ,\"Strategic\",VHF!$BB:$BB,\"Match\",VHF!$AK:$AK,'JPM Data Converted (Paymode VC)'!G$2)"
    }
   ],
   [
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    }
   ],
   [
    {
     "v": "Virtual Card"
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    }
   ],
   [
    {
     "v": ""
    },
    {
     "v": "Total"
    },
    {
     "v": "Check to VC"
    },
    {
     "v": "ACH to VC"
    },
    {
     "v": "PMX Classic ACH to VC"
    },
    {
     "v": "VC Card Migration"
    },
    {
     "v": "Wire to VC"
    }
   ],
   [
    {
     "v": "Campaign Vendors"
    },
    {
     "v": "80",
     "f": "=Calculations!V10-B27-B31"
    },
    {
     "v": "68",
     "f": "=Calculations!Q10-C27-C31"
    },
    {
     "v": "12",
     "f": "=Calculations!R10-D27-D31"
    },
    {
     "v": "0",
     "f": "=Calculations!S10-E27-E31"
    },
    {
     "v": "0",
     "f": "=Calculations!U10-F27-F31"
    },
    {
     "v": "0",
     "f": "=Calculations!T10-G27-G31"
    }
   ],
   [
    {
     "v": "Campaign Transactions"
    },
    {
     "v": "1,032",
     "f": "=Calculations!P10-B28-B32"
    },
    {
     "v": "689",
     "f": "=Calculations!K10-C28-C32"
    },
    {
     "v": "343",
     "f": "=Calculations!L10-D28-D32"
    },
    {
     "v": "0",
     "f": "=Calculations!M10-E28-E32"
    },
    {
     "v": "0",
     "f": "=Calculations!O10-F28-F32"
    },
    {
     "v": "0",
     "f": "=Calculations!N10-G28-G32"
    }
   ],
   [
    {
     "v": "Campaign Spend"
    },
    {
     "v": "18,434,686.70",
     "f": "=Calculations!J10-B29-B33"
    },
    {
     "v": "9,868,723.64",
     "f": "=Calculations!E10-C29-C33"
    },
    {
     "v": "8,565,963.06",
     "f": "=Calculations!F10-D29-D33"
    },
    {
     "v": "0",
     "f": "=Calculations!G10-E29-E33"
    },
    {
     "v": "0",
     "f": "=Calculations!I10-F29-F33"
    },
    {
     "v": "0",
     "f": "=Calculations!H10-G29-G33"
    }
   ],
   [
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    }
   ],
   [
    {
     "v": "Virtual Card Migration Vendors"
    },
    {
     "v": "0",
     "f": "=Calculations!V11"
    },
    {
     "v": "0",
     "f": "=Calculations!Q11"
    },
    {
     "v": "0",
     "f": "=Calculations!R11"
    },
    {
     "v": "0",
     "f": "=Calculations!S11"
    },
    {
     "v": "0",
     "f": "=Calculations!U11"
    },
    {
     "v": "0",
     "f": "=Calculations!T11"
    }
   ],
   [
    {
     "v": "Virtual Card Migration Transactions"
    },
    {
     "v": "0",
     "f": "=Calculations!P11"
    },
    {
     "v": "0",
     "f": "=Calculations!K11"
    },
    {
     "v": "0",
     "f": "=Calculations!L11"
    },
    {
     "v": "0",
     "f": "=Calculations!M11"
    },
    {
     "v": "0",
     "f": "=Calculations!O11"
    },
    {
     "v": "0",
     "f": "=Calculations!N11"
    }
   ],
   [
    {
     "v": "Virtual Card Migration Spend"
    },
    {
     "v": "0",
     "f": "=Calculations!J11"
    },
    {
     "v": "0",
     "f": "=Calculations!E11"
    },
    {
     "v": "0",
     "f": "=Calculations!F11"
    },
    {
     "v": "0",
     "f": "=Calculations!G11"
    },
    {
     "v": "0",
     "f": "=Calculations!I11"
    },
    {
     "v": "0",
     "f": "=Calculations!H11"
    }
   ],
   [
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    }
   ],
   [
    {
     "v": "Day One Card Vendors"
    },
    {
     "v": "50",
     "f": "=Calculations!V12+Calculations!V13"
    },
    {
     "v": "47",
     "f": "=Calculations!Q12+Calculations!Q13"
    },
    {
     "v": "3",
     "f": "=Calculations!R12+Calculations!R13"
    },
    {
     "v": "0",
     "f": "=Calculations!S12+Calculations!S13"
    },
    {
     "v": "0",
     "f": "=Calculations!U12+Calculations!U13"
    },
    {
     "v": "0",
     "f": "=Calculations!T12+Calculations!T13"
    }
   ],
   [
    {
     "v": "Day One Card Transactions"
    },
    {
     "v": "531",
     "f": "=Calculations!P12+Calculations!P13"
    },
    {
     "v": "465",
     "f": "=Calculations!K12+Calculations!K13"
    },
    {
     "v": "66",
     "f": "=Calculations!L12+Calculations!L13"
    },
    {
     "v": "0",
     "f": "=Calculations!M12+Calculations!M13"
    },
    {
     "v": "0",
     "f": "=Calculations!O12+Calculations!O13"
    },
    {
     "v": "0",
     "f": "=Calculations!N12+Calculations!N13"
    }
   ],
   [
    {
     "v": "Day One Card Spend"
    },
    {
     "v": "3,879,834.90",
     "f": "=Calculations!J12+Calculations!J13"
    },
    {
     "v": "3,850,763.94",
     "f": "=Calculations!E12+Calculations!E13"
    },
    {
     "v": "29,070.96",
     "f": "=Calculations!F12+Calculations!F13"
    },
    {
     "v": "0",
     "f": "=Calculations!G12+Calculations!G13"
    },
    {
     "v": "0",
     "f": "=Calculations!I12+Calculations!I13"
    },
    {
     "v": "0",
     "f": "=Calculations!H12+Calculations!H13"
    }
   ],
   [
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    }
   ]
  ]
 },
 {
  "name": "Variables Internal",
  "startRow": 5,
  "startCol": 2,
  "headerRows": 1,
  "input": false,
  "rows": [
   [
    {
     "v": "Opportunity Details"
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    }
   ],
   [
    {
     "v": "Prospect / Client:"
    },
    {
     "v": "Denton County Electric Cooperative"
    },
    {
     "v": ""
    },
    {
     "v": "Analysis Date"
    },
    {
     "v": "2026-01-16 00:00:00",
     "f": "=C7"
    }
   ],
   [
    {
     "v": "Date"
    },
    {
     "v": "2026-01-16 00:00:00"
    },
    {
     "v": ""
    },
    {
     "v": "Total # of AP Vendors"
    },
    {
     "v": "625",
     "f": "=Calculations!V5"
    }
   ],
   [
    {
     "v": "Pricing Analyst"
    },
    {
     "v": "Nolan Mann"
    },
    {
     "v": ""
    },
    {
     "v": "Total $ of AP Spend"
    },
    {
     "v": "761,331,684.49",
     "f": "=Calculations!J5"
    }
   ],
   [
    {
     "v": "Internal Sales Rep"
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": "Total # of AP Transactions"
    },
    {
     "v": "5,981",
     "f": "=Calculations!P5"
    }
   ],
   [
    {
     "v": "Channel Sales Rep"
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": "Old ARR Values"
    },
    {
     "v": ""
    }
   ],
   [
    {
     "v": "Sales Channel"
    },
    {
     "v": "JPM"
    },
    {
     "v": ""
    },
    {
     "v": "BT ARR - Card"
    },
    {
     "v": "0",
     "f": "=Calculations!J25*Lookup!C53"
    }
   ],
   [
    {
     "v": "Opportunity Type"
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": "BT ARR - Premium ACH"
    },
    {
     "v": "141,199.60",
     "f": "=Calculations!J68*Lookup!C55*Lookup!C56"
    }
   ],
   [
    {
     "v": "Pricing Types"
    },
    {
     "v": "Premium, Basic, Card, Check Print"
    },
    {
     "v": ""
    },
    {
     "v": "BT ARR - Basic Transactions"
    },
    {
     "v": "734.97",
     "f": "=Calculations!P108*Lookup!C57"
    }
   ],
   [
    {
     "v": "NaaS - Open + Selective Acceptor Booking Only"
    },
    {
     "v": "No"
    },
    {
     "v": ""
    },
    {
     "v": "BT ARR - Check Print"
    },
    {
     "v": "0",
     "f": "=Calculations!P130*Lookup!C58"
    }
   ],
   [
    {
     "v": "NaaS - Open Acceptor Booking Only"
    },
    {
     "v": "No"
    },
    {
     "v": ""
    },
    {
     "v": "BT ARR - B2C Payments"
    },
    {
     "v": "0",
     "f": "=(Calculations!P355*Lookup!C57)+(Calculations!P356*Lookup!C58)"
    }
   ],
   [
    {
     "v": "Clent Preference for Legacy Payment Method"
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": "BT ARR - Invoice Automation"
    },
    {
     "v": "0"
    }
   ],
   [
    {
     "v": "Vendors Paid by Card today"
    },
    {
     "v": "Include"
    },
    {
     "v": ""
    },
    {
     "v": "Basic Vendor Setup Fees"
    },
    {
     "v": "5,674.22",
     "f": "=(Calculations!V108-Calculations!S108)*Lookup!C59"
    }
   ],
   [
    {
     "v": "Vendors Paid by Wire today"
    },
    {
     "v": "Include"
    },
    {
     "v": ""
    },
    {
     "v": "Channel Card Revenue"
    },
    {
     "v": "0",
     "f": "=Calculations!J25*Lookup!C54"
    }
   ],
   [
    {
     "v": "Vendors Paid by ACH today"
    },
    {
     "v": "Include"
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    }
   ],
   [
    {
     "v": "Vendors Paid by Check today"
    },
    {
     "v": "Include"
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    }
   ]
  ]
 },
 {
  "name": "Pricing Details for SF",
  "startRow": 1,
  "startCol": 1,
  "headerRows": 2,
  "input": false,
  "rows": [
   [
    {
     "v": "SF Database Field Names"
    },
    {
     "v": "Id"
    },
    {
     "v": "of_Paymode_X_Card_Matches_of_Total_Ven__c"
    },
    {
     "v": "of_PNMN_Vendors_DIV__c"
    },
    {
     "v": "of_PMNM_Checks_DIV__c"
    },
    {
     "v": "Virtual_Card_Migration_Spend__c"
    },
    {
     "v": "Virtual_Card_Migration_Transactions__c"
    },
    {
     "v": "Virtual_Card_Migration_Vendors__c"
    },
    {
     "v": "Card_Exact_Match_Spend__c"
    },
    {
     "v": "Card_Exact_Match_Transactions__c"
    },
    {
     "v": "Card_Exact_Match_Vendors__c"
    },
    {
     "v": "Card_Target_Spend__c"
    }
   ],
   [
    {
     "v": "SF UI Name"
    },
    {
     "v": "Pricing SF Record ID"
    },
    {
     "v": "% of Paymode-X Card Matches of Total Ven"
    },
    {
     "v": "% of PNMN Vendors (DIV)"
    },
    {
     "v": "% of PMNM Checks (DIV)"
    },
    {
     "v": "Virtual Card Migration Spend"
    },
    {
     "v": "Virtual Card Migration Transactions"
    },
    {
     "v": "Virtual Card Migration Vendors"
    },
    {
     "v": "Card Exact Match Spend"
    },
    {
     "v": "Card Exact Match Transactions"
    },
    {
     "v": "Card Exact Match Vendors"
    },
    {
     "v": "Card Target Spend"
    }
   ],
   [
    {
     "v": "Pricing Analyst Notes"
    },
    {
     "v": ""
    },
    {
     "v": "% of Paymode-X Card Matches"
    },
    {
     "v": "% of Vendors Matching to the Network of Total Vendor File"
    },
    {
     "v": "% of Transactions Matching to the Network of Total Vendor File"
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    },
    {
     "v": ""
    }
   ],
   [
    {
     "v": ""
    },
    {
     "v": "a9IWy000000a7hJMAQ"
    },
    {
     "v": "8.64",
     "f": "=(SUM(Calculations!V12,Calculations!V14)/Calculations!V5)*100"
    },
    {
     "v": "27.20",
     "f": "=(Calculations!V219/Calculations!V5)*100"
    },
    {
     "v": "34.78",
     "f": "=(Calculations!P219/Calculations!P5)*100"
    },
    {
     "v": "0",
     "f": "=Calculations!J11"
    },
    {
     "v": "0",
     "f": "=Calculations!P11"
    },
    {
     "v": "0",
     "f": "=Calculations!V11"
    },
    {
     "v": "3,879,834.90",
     "f": "=SUM(Calculations!J12:J13)"
    },
    {
     "v": "531",
     "f": "=SUM(Calculations!P12:P13)"
    },
    {
     "v": "50",
     "f": "=SUM(Calculations!V12:V13)"
    },
    {
     "v": "18,434,686.70",
     "f": "=SUM(Calculations!J14:J17)"
    }
   ],
   [
    {
     "v": "For Channel Change Only"
    },
    {
     "v": ""
    },
    {
     "v": "0"
    },
    {
     "v": "0"
    },
    {
     "v": "0"
    },
    {
     "v": "0"
    },
    {
     "v": "0"
    },
    {
     "v": "0"
    },
    {
     "v": "0"
    },
    {
     "v": "0"
    },
    {
     "v": "0"
    },
    {
     "v": "0"
    }
   ]
  ]
 }
];
