"""Emit lib/deckRender.ts — the filmstrip manifest for the pre-rendered slide PNGs.

Titles are read back out of the generated deck so the manifest can never drift
from the images sitting in public/deck.

Usage:
    python slide_manifest.py --deck <generated.pptx> --out <lib/deckRender.ts>
"""

import argparse
import json

from pptx import Presentation
from pptx.enum.shapes import PP_PLACEHOLDER
from pptx.oxml.ns import qn

TITLE_TYPES = {PP_PLACEHOLDER.TITLE, PP_PLACEHOLDER.CENTER_TITLE}


def paragraph_text(p) -> str:
    # Walk the XML rather than p.runs so <a:br> line breaks become spaces instead
    # of vanishing and welding two runs together.
    parts = []
    for child in p._p:
        if child.tag == qn('a:r'):
            node = child.find(qn('a:t'))
            parts.append(node.text or '')
        elif child.tag == qn('a:br'):
            parts.append(' ')
    return ''.join(parts).strip()


def shape_text(shape) -> str:
    lines = [paragraph_text(p) for p in shape.text_frame.paragraphs]
    return ' '.join(l for l in lines if l).strip()


def slide_title(slide, n: int) -> str:
    fallback = ''
    for shp in slide.shapes:
        if not shp.has_text_frame:
            continue
        text = shape_text(shp)
        if not text:
            continue
        ph = shp.placeholder_format.type if shp.is_placeholder else None
        if ph in TITLE_TYPES:
            return text
        if not fallback:
            fallback = text
    return fallback or f'Slide {n}'


def manifest(key: str, path: str) -> list:
    prs = Presentation(path)
    return [
        {
            'n': n,
            'src': f'/deck/{key}/slide-{n:02d}.png',
            'title': slide_title(slide, n)[:120],
        }
        for n, slide in enumerate(prs.slides, start=1)
    ]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--deck', action='append', required=True, help='key=path/to/generated.pptx')
    ap.add_argument('--out', required=True)
    args = ap.parse_args()

    decks = {}
    for spec in args.deck:
        key, _, path = spec.partition('=')
        decks[key] = manifest(key, path)

    blocks = []
    for key, slides in decks.items():
        rows = ',\n'.join('    ' + json.dumps(s) for s in slides)
        blocks.append(f'  {json.dumps(key)}: [\n{rows},\n  ],')

    with open(args.out, 'w', encoding='utf-8') as fh:
        fh.write(
            '// GENERATED by scripts/render-deck-slides.ps1 — do not edit by hand.\n'
            '// Each entry points at a PNG exported from the deck the app actually\n'
            '// generates, so the step 7 preview and the downloaded file are the\n'
            '// same artifact. Keyed by deck map: one bank template per deal.\n\n'
            'export interface DeckRenderSlide {\n'
            '  n: number;\n'
            '  src: string;\n'
            '  title: string;\n'
            '}\n\n'
            'export const deckRenderSlidesByDeck: Record<string, DeckRenderSlide[]> = {\n'
            + '\n'.join(blocks)
            + '\n};\n\n'
            '/** Slides for a deck map, or [] for deals that never produced a deck. */\n'
            'export function deckSlidesFor(deckMap: string | undefined): DeckRenderSlide[] {\n'
            '  if (!deckMap) return [];\n'
            '  return deckRenderSlidesByDeck[deckMap] ?? [];\n'
            '}\n'
        )
    print(json.dumps({'status': 'ok', 'decks': {k: len(v) for k, v in decks.items()}}))


if __name__ == '__main__':
    main()
