// ============================================================
//  Run data — Bank of America / Authentic Brands Group
//  Every figure below was read from the real POC deal files in
//  POC Deals/BOA. Preview tables come from abgPreviews.ts,
//  which is generated by POC Deals/_dump/build_previews.py.
//
//  Two things make this deal different to the other two:
//   1. It never produced an ROI slide deck — the bank took the
//      external value model workbook only. Step 7 says so.
//   2. The bank asked for two commercial scenarios, so files 8
//      and 9 exist in a CompPay and a PM Only variant. See
//      `scenarios` at the bottom of this file.
// ============================================================

import { abgPreviews } from '../previews/abgPreviews';
import type { DealDefinition, DealMeta, DealScenario, StageRun } from './types';

export const DEAL: DealMeta = {
  id: 'abg-bofa',
  client: 'Authentic Brands Group',
  channel: 'Bank of America',
  analyst: 'Pricing Ops',
  received: '2026-05-18',
};

export const stageRuns: Record<string, StageRun> = {
  intake: {
    metrics: [
      { label: 'Vendor rows', value: '1,516', sub: 'plus 1 template example row' },
      { label: 'Columns detected', value: '21' },
      { label: 'Total spend', value: '$148.4M', sub: '12,481 payments' },
    ],
    checks: [
      { id: 'vendor', label: 'Merchant Name', status: 'pass', detail: 'Present on all 1,516 vendor rows.' },
      { id: 'spend', label: 'Total Spend', status: 'pass', detail: 'Numeric on every row; totals $148,366,871.39.' },
      { id: 'counts', label: 'Payment counts', status: 'pass', detail: '12,481 payments across 1,516 vendors.' },
      {
        id: 'example-row',
        label: 'Template example row',
        status: 'warn',
        detail:
          'Row 1 is the blank template\u2019s worked example (Payment Type "Check, ACH, Wire") rather than a real vendor. ' +
          'It is the only row with Tax ID, Terms and Contact filled in.',
        action: 'Dropped before cleaning \u2014 1,517 rows in, 1,516 vendors carried forward.',
      },
      {
        id: 'ptype',
        label: 'Payment Type',
        status: 'warn',
        detail:
          'Values are the bank\u2019s own codes: ACH (1,160), SWIFT (168), INT (118), ' +
          'PAID_MAN (41), D_WIRE (29). No Check and no Card.',
        action: 'Needs a normalisation map \u2014 four of these five codes have to be resolved to ACH or Wire.',
      },
      {
        id: 'addr',
        label: 'Address block',
        status: 'warn',
        detail: 'Address, City, State and Postal Code are filled on 1,378 of 1,516 vendors (90.9%). 138 vendors have none.',
        action: 'Good enough to submit \u2014 the 138 blanks will match on name alone and are expected to underperform.',
      },
      {
        id: 'tin',
        label: 'Tax ID',
        status: 'fail',
        detail: 'Empty on all 1,516 real vendor rows. The only populated value belongs to the template example row.',
        action: 'Ask the bank for tax IDs \u2014 without them the network match falls back to name and address only.',
        emailDraft: {
          to: 'operations@bofa.com',
          subject: 'Authentic Brands Group \u2014 vendor file is missing Tax ID and contact fields',
          body:
            'Hi,\n\n' +
            'Thanks for the Authentic Brands Group AP file. Before we submit it for the network match, two things:\n\n' +
            '1. Tax ID is empty on all 1,516 vendor rows, as are Email Address, Contact Name and Phone. ' +
            'Only the template\u2019s worked example row has them filled in, so we assume the extract dropped those columns.\n\n' +
            '2. Payment Type comes through as ACH / SWIFT / INT / PAID_MAN / D_WIRE. ' +
            'Could you confirm PAID_MAN is a manually released ACH \u2014 that is how we are treating it.\n\n' +
            'We can proceed without the tax IDs, but the match rate will be lower and we would rather flag that now than explain it later.\n\n' +
            'Thanks,\nPricing Ops',
        },
      },
      {
        id: 'email',
        label: 'Vendor email / contact',
        status: 'fail',
        detail: 'Email Address, Contact Name and Phone are empty on all 1,516 rows.',
        action: 'Enablement outreach cannot start from this file \u2014 request contacts separately.',
      },
      {
        id: 'invoices',
        label: 'Invoice counts',
        status: 'warn',
        detail: 'Number of Invoices is zero on every row, so invoice-automation value cannot be modelled for this deal.',
      },
    ],
    previews: {
      '1_ORIGINAL_VENDOR_FILE.xlsx': abgPreviews['1_ORIGINAL_VENDOR_FILE.xlsx'],
      'intake_check_report.json': abgPreviews['intake_check_report.json'],
    },
  },

  'alteryx-clean': {
    metrics: [
      { label: 'Rows in', value: '1,517', sub: 'incl. template example row' },
      { label: 'Vendors out', value: '1,516' },
      { label: 'Columns out', value: '13', sub: 'from 21 submitted' },
    ],
    transforms: [
      { label: 'Drop', detail: 'The template example row is removed \u2014 1,517 in, 1,516 out.' },
      { label: 'No grouping', detail: 'This bank already sends one row per vendor, so there is no payment-level collapse.' },
      { label: 'Rename', detail: 'Merchant Name \u2192 Vendor Name, Address \u2192 Remittance Line 1, State Codes \u2192 State.' },
      {
        label: 'Normalize',
        detail:
          'Payment Type is mapped to the model\u2019s vocabulary: ACH and PAID_MAN become ACH (1,201 vendors); ' +
          'SWIFT, INT and D_WIRE become Wire (315 vendors).',
      },
      { label: 'Carry', detail: 'Total Spend and Number of Payments carried through unchanged.' },
    ],
    checks: [
      { id: 'grain', label: 'Row count as expected', status: 'pass', detail: '1,517 rows in, 1,516 vendors out \u2014 only the example row was dropped.' },
      { id: 'spend-tie', label: 'Spend ties to source', status: 'pass', detail: 'Sum of vendor spend = $148,366,871.39, matches the raw file total.' },
      { id: 'ptype-norm', label: 'Payment type normalized', status: 'pass', detail: 'Five bank codes resolved to ACH (1,201 vendors) and Wire (315 vendors).' },
      {
        id: 'addr-gap',
        label: 'Address gaps carried forward',
        status: 'warn',
        detail: '138 vendors still have no address \u2014 the source file never supplied one.',
        action: 'Expect these to match on name alone.',
      },
    ],
    previews: {
      '2_Mapping_Document.xlsx': abgPreviews['2_Mapping_Document.xlsx'],
      '3_Alteryx_Cleaning_Output.xlsx': abgPreviews['3_Alteryx_Cleaning_Output.xlsx'],
      '4_ROC_Upload_VHFCleaned.xlsx': abgPreviews['4_ROC_Upload_VHFCleaned.xlsx'],
    },
  },

  'roc-match': {
    metrics: [
      { label: 'Vendors submitted', value: '1,516' },
      { label: 'Mastercard detail', value: '1,189', sub: '78.4% of vendors' },
      { label: 'Potential ROC match', value: '417', sub: '27.5% of vendors' },
    ],
    checks: [
      { id: 'rowcount', label: 'Row count preserved', status: 'pass', detail: '1,516 rows in, 1,516 rows out \u2014 ROC enriches 1:1.' },
      { id: 'enrich', label: 'Enrichment columns returned', status: 'pass', detail: '85 columns returned, 80 of them new.' },
      { id: 'mc', label: 'Mastercard match', status: 'pass', detail: 'Mastercard status returned for 1,189 of 1,516 vendors.' },
      {
        id: 'visa',
        label: 'Visa match',
        status: 'warn',
        detail: 'Visa Matched is empty on all 1,516 rows for this submission.',
        action: 'Confirm with ROC whether the Visa file was run before relying on card projections.',
      },
      {
        id: 'epp',
        label: 'Existing network members',
        status: 'pass',
        detail: '1 exact and 17 probable EPP matches \u2014 almost none of this file is already on the network.',
      },
    ],
    previews: {
      '5_ROC_pricing_export.xlsx': abgPreviews['5_ROC_pricing_export.xlsx'],
    },
  },

  'alteryx-pricing': {
    metrics: [
      { label: 'Vendors segmented', value: '1,516' },
      { label: 'Campaign targets', value: '1,213', sub: '$116.8M spend' },
      { label: 'Network matches', value: '191', sub: '$36.4M spend' },
    ],
    checks: [
      { id: 'rowcount', label: 'Row count preserved', status: 'pass', detail: '1,516 in, 1,516 out.' },
      { id: 'segment', label: 'Segment assigned', status: 'pass', detail: 'Every vendor carries a pricing segment label.' },
      { id: 'excl', label: 'Exclusions applied', status: 'pass', detail: '303 vendors excluded from the campaign, leaving 1,213 targets.' },
      { id: 'cap', label: 'Fee cap fields', status: 'pass', detail: 'Cap Type populated on all rows.' },
    ],
    previews: {
      '6_Alteryx_PricingOutput.xlsx': abgPreviews['6_Alteryx_PricingOutput.xlsx'],
    },
  },

  classification: {
    metrics: [
      { label: 'Rules applied', value: '2' },
      { label: 'Segments overridden', value: '3' },
      { label: 'Exceptions for review', value: '0' },
    ],
    transforms: [
      {
        label: 'Rule 1 \u00b7 Related entity',
        detail:
          'Vendors that are sports or entertainment properties under common ownership are not genuine network members. ' +
          'Caught Madison Square Garden Sports Corp. and New York Yankees Partnership.',
      },
      {
        label: 'Rule 2 \u00b7 Card-capable service vendor',
        detail: 'Talent and model agencies do accept card despite a weak network signal. Caught 1 Model Management, LLC.',
      },
      { label: 'Rule 3 \u00b7 Otherwise', detail: 'Keep the Alteryx segment. If entity type is unclear, raise an exception instead of guessing.' },
    ],
    overrides: [
      {
        vendor: 'Madison Square Garden Sports Corp.',
        segmentBefore: 'Paymode Network Match',
        segmentAfter: 'Basic Match',
        reason: 'Related entity, not a genuine network member.',
      },
      {
        vendor: 'New York Yankees Partnership',
        segmentBefore: 'Paymode Network Match',
        segmentAfter: 'Basic Match',
        reason: 'Related entity, not a genuine network member.',
      },
      {
        vendor: '1 Model Management, LLC',
        segmentBefore: 'Basic Match',
        segmentAfter: 'Card Target - Network Match - Low',
        reason: 'Talent agency \u2014 accepts card, worth targeting.',
      },
    ],
    checks: [
      { id: 'rowcount', label: 'Row count preserved', status: 'pass', detail: '1,516 in, 1,516 out. No rows added or lost.' },
      { id: 'labels', label: 'Segment labels valid', status: 'pass', detail: 'All values exist in the segment mapping table.' },
      { id: 'spend-mix', label: 'Spend mix reasonable', status: 'pass', detail: 'Three vendors moved; total spend unchanged at $148,366,871.39.' },
      { id: 'exceptions', label: 'Low-confidence rows', status: 'pass', detail: 'No vendor needed an analyst decision on this file.' },
    ],
    previews: {
      '7_Reviewed_PricingOutput_MR.xlsx': abgPreviews['7_Reviewed_PricingOutput_MR.xlsx'],
    },
  },

  'value-statement': {
    metrics: [
      { label: 'Total file spend', value: '$148.4M', sub: '12,481 transactions' },
      { label: 'Campaign target spend', value: '$116.8M', sub: '78.7% of file' },
      { label: 'Network matched spend', value: '$36.4M', sub: '191 vendors' },
      { label: 'Open acceptor value', value: '$5.4M', sub: '38 day-one card vendors' },
    ],
    checks: [
      { id: 'file-totals', label: 'File totals tie to source', status: 'pass', detail: '1,516 vendors / 12,481 transactions / $148,366,871.39.' },
      { id: 'split', label: 'Spend split reconciles', status: 'pass', detail: 'ACH $126.75M + Wire $21.62M = $148.37M total. No check or card spend in this file.' },
      { id: 'formula', label: 'Formula health', status: 'pass', detail: 'No errors on Calculations, Booking Calc or the BofA conversion tab.' },
      { id: 'projection', label: 'Projection sanity', status: 'pass', detail: 'No negative projections.' },
      {
        id: 'scenarios',
        label: 'Two commercial scenarios',
        status: 'warn',
        detail:
          'The bank asked for both Comprehensive Payables and Paymode Connect only, so this file exists twice. ' +
          'The conversion tab is identical in both \u2014 they diverge in the card program.',
        action: 'Use the scenario switch above the metrics to compare them.',
      },
      {
        id: 'card-qa',
        label: 'Card projection depends on Mastercard',
        status: 'warn',
        detail: 'Visa returned no matches, so card projections lean entirely on Mastercard detail.',
        action: 'Sanity-check the card projection with the bank before it goes external.',
      },
    ],
    previews: {
      '8_Internal_Value_Statement.xlsx': abgPreviews['8_Internal_Value_Statement.xlsx'],
    },
  },

  'external-roi': {
    metrics: [
      { label: 'Slides generated', value: 'None', sub: 'this deal produced no deck' },
      { label: 'External workbook', value: '1', sub: 'value model, both scenarios' },
      { label: 'Program lines', value: '2', sub: 'card and ACH conversion' },
    ],
    checks: [
      {
        id: 'no-deck',
        label: 'No ROI deck for this deal',
        status: 'warn',
        detail:
          'The BofA folder contains no PowerPoint. This deal was delivered as the external value model workbook only, ' +
          'so there is nothing for the deck engine to render.',
        action: 'If the bank later asks for slides, the workbook has everything needed to build them.',
      },
      { id: 'trace', label: 'Workbook figures trace to source', status: 'pass', detail: 'Every figure in the external model maps to a cell on the converted tab.' },
      { id: 'internal', label: 'No internal-only fields', status: 'pass', detail: 'Internal pricing fields excluded from the external workbook.' },
      { id: 'header', label: 'Header consistency', status: 'pass', detail: 'Client name, date and channel identical across both scenario workbooks.' },
    ],
    previews: {
      '9_External_ROI_Analysis.xlsx': abgPreviews['9_External_ROI_Analysis.xlsx'],
    },
  },

  sendback: {
    metrics: [
      { label: 'Recipients', value: '3', sub: '1 to \u00b7 2 cc' },
      { label: 'Package attached', value: '2 files', sub: 'one per scenario' },
      { label: 'Internal copy', value: 'File 8', sub: 'pricing team only' },
    ],
    checks: [
      { id: 'attach', label: 'Attachments present', status: 'pass', detail: 'Both external value models attached \u2014 CompPay and PM Only.' },
      { id: 'internal-split', label: 'Internal file withheld', status: 'pass', detail: 'The internal value statement is not attached to the bank-facing email.' },
      { id: 'recipients', label: 'Recipients resolved', status: 'pass', detail: 'Taken from the original analysis request thread.' },
      {
        id: 'no-deck-note',
        label: 'No deck to attach',
        status: 'pass',
        detail: 'The covering note says the analysis is workbook-only, so the bank is not left waiting for slides.',
      },
    ],
    previews: {},
  },

  salesforce: {
    metrics: [
      { label: 'Records updated', value: '1' },
      { label: 'Opportunity', value: 'Not linked', sub: 'no SF opportunity on this deal' },
    ],
    checks: [
      { id: 'conn', label: 'Salesforce connection', status: 'pass', detail: 'Authenticated against the pricing sandbox.' },
      { id: 'fields', label: 'Required fields populated', status: 'pass', detail: 'All Calc_* pricing fields written.' },
      {
        id: 'opp',
        label: 'Opportunity link',
        status: 'warn',
        detail: 'This pricing has no Salesforce opportunity attached.',
        action: 'Ask the channel team to create or link the opportunity so the pricing can be reported on.',
      },
    ],
    previews: {
      'salesforce_sync_receipt.json': abgPreviews['salesforce_sync_receipt.json'],
    },
  },
};

/**
 * The bank priced this deal two ways. Both scenarios share one vendor file and
 * one converted tab — the numbers below are the ones that actually differ,
 * read from the Dashboard tab of each external value model.
 */
export const scenarios: DealScenario[] = [
  {
    id: 'comppay',
    label: 'Comprehensive Payables',
    description: 'Virtual card plus Paymode Connect. 44 suppliers convert to card, the rest to ACH.',
    metrics: {
      'value-statement': [
        { label: 'Total file spend', value: '$148.4M', sub: '12,481 transactions' },
        { label: 'Card conversion', value: '44 suppliers', sub: '441 transactions' },
        { label: 'ACH conversion', value: '1,147 suppliers', sub: '5,864 transactions' },
        { label: 'Electronic conversion', value: '78.6%', sub: 'of program targets' },
      ],
      'external-roi': [
        { label: 'Slides generated', value: 'None', sub: 'this deal produced no deck' },
        { label: 'External workbook', value: 'CompPay', sub: 'virtual payables + connect' },
        { label: 'Program lines', value: '2', sub: 'card and ACH conversion' },
      ],
    },
  },
  {
    id: 'pm-only',
    label: 'Paymode Connect only',
    description: 'No card programme. Every converting supplier moves to ACH instead.',
    metrics: {
      'value-statement': [
        { label: 'Total file spend', value: '$148.4M', sub: '12,481 transactions' },
        { label: 'Card conversion', value: 'None', sub: 'no card programme' },
        { label: 'ACH conversion', value: '1,192 suppliers', sub: '6,305 transactions' },
        { label: 'Electronic conversion', value: '78.6%', sub: 'of program targets' },
      ],
      'external-roi': [
        { label: 'Slides generated', value: 'None', sub: 'this deal produced no deck' },
        { label: 'External workbook', value: 'PM Only', sub: 'connect without card' },
        { label: 'Program lines', value: '1', sub: 'ACH conversion' },
      ],
    },
  },
];

export const abgDeal: DealDefinition = {
  meta: DEAL,
  stageRuns,
  // BofA was delivered as value models — this deal never produced a deck.
  deckMap: null,
  scenarios,
};
