// ============================================================
//  Run data — Fifth Third / Illume Ag
//  Every figure below was read from the real POC deal files in
//  POC Deals/53. Preview tables come from illumePreviews.ts,
//  which is generated by POC Deals/_dump/build_previews.py.
// ============================================================

import { illumePreviews, illumeSlides } from '../previews/illumePreviews';
import type { DealDefinition, DealMeta, StageRun } from './types';

export const DEAL: DealMeta = {
  id: 'illume-ag-53',
  client: 'Illume Ag',
  channel: 'Fifth Third Bank',
  analyst: 'Pricing Ops',
  received: '2025-11-04',
};

export const stageRuns: Record<string, StageRun> = {
  intake: {
    metrics: [
      { label: 'Vendor rows', value: '466' },
      { label: 'Columns detected', value: '16' },
      { label: 'Coverage', value: '12 months', sub: 'rolling, per vendor' },
    ],
    checks: [
      { id: 'vendor', label: 'Merchant Name', status: 'pass', detail: 'Present on all 466 rows.' },
      { id: 'spend', label: 'Spend (rolling 12 months)', status: 'pass', detail: 'Numeric on every row; totals $21,834,520.76.' },
      { id: 'counts', label: 'Payment / invoice counts', status: 'pass', detail: '3,666 payments across 8,196 invoices.' },
      { id: 'ptype', label: 'Payment Type', status: 'pass', detail: 'Values are CARD (243) / Check (192) / ACH (31).' },
      {
        id: 'addr',
        label: 'Address block',
        status: 'fail',
        detail: 'State, City and ZIP are empty on all 466 rows. Street address is a single concatenated field.',
        action: 'Ask the bank for split City / State / ZIP — address quality drives the ROC match rate.',
        emailDraft: {
          to: 'operations@53.com',
          subject: 'Illume Ag — missing City / State / ZIP on the vendor file',
          body:
            'Hi,\n\n' +
            'Thanks for the Illume Ag vendor file. Before we run the network match, could you confirm the address fields?\n\n' +
            'All 466 vendor rows have City, State and ZIP empty — the street address arrives as one concatenated block. ' +
            'Split address fields materially improve the match rate, so we would rather re-run with them than match on name alone.\n\n' +
            'If the source system cannot split them, let us know and we will parse the concatenated field and flag anything ambiguous.\n\n' +
            'Thanks,\nPricing Ops',
        },
      },
      {
        id: 'tin',
        label: 'Tax ID',
        status: 'warn',
        detail: '295 of 466 vendors have no tax ID (36.7% populated). Not blocking — noted for match quality.',
        action: 'Request tax IDs for the 295 vendors missing one.',
      },
      { id: 'email', label: 'Vendor email', status: 'warn', detail: 'Empty on all rows. Enablement outreach will need contacts later.' },
    ],
    previews: {
      '1_ORIGINAL_VENDOR_FILE.xlsx': illumePreviews['1_ORIGINAL_VENDOR_FILE.xlsx'],
      'intake_check_report.json': illumePreviews['intake_check_report.json'],
    },
  },

  'alteryx-clean': {
    metrics: [
      { label: 'Rows in', value: '466', sub: 'already vendor level' },
      { label: 'Vendors out', value: '466', sub: 'no collapse needed' },
      { label: 'Columns added', value: '3', sub: 'normalised terms + country' },
    ],
    transforms: [
      { label: 'No grouping', detail: 'This bank sends one row per vendor, so there is no payment-level collapse — 466 in, 466 out.' },
      { label: 'Rename', detail: 'Merchant Name → Vendor Name, street block → Remittance Line 1-3, Tax ID kept.' },
      { label: 'Normalize', detail: 'CARD → Card, Check stays Check, ACH stays ACH.' },
      { label: 'Derive', detail: 'Discount Terms normalised and a Term Category assigned from the raw Terms text.' },
      { label: 'Carry', detail: 'Spend, Transactions and Invoices carried through unchanged.' },
    ],
    checks: [
      { id: 'grain', label: 'Row count preserved', status: 'pass', detail: '466 vendor rows in, 466 out.' },
      { id: 'spend-tie', label: 'Spend ties to source', status: 'pass', detail: 'Sum of vendor Spend = $21,834,520.76, matches the raw file total.' },
      { id: 'ptype-norm', label: 'Payment type normalized', status: 'pass', detail: 'Only Card / Check / ACH remain.' },
      {
        id: 'addr-gap',
        label: 'Address still incomplete',
        status: 'warn',
        detail: 'City / State / ZIP could not be filled — the source file never supplied them.',
        action: 'Expect a lower network match rate than a deal with a full address block.',
      },
    ],
    previews: {
      '2_Mapping_Document.xlsx': illumePreviews['2_Mapping_Document.xlsx'],
      '3_Alteryx_Cleaning_Output.xlsx': illumePreviews['3_Alteryx_Cleaning_Output.xlsx'],
      '4_ROC_Upload_VHFCleaned.xlsx': illumePreviews['4_ROC_Upload_VHFCleaned.xlsx'],
    },
  },

  'roc-match': {
    metrics: [
      { label: 'Vendors submitted', value: '466' },
      { label: 'Network matches', value: '75', sub: '16% of vendors' },
      { label: 'Matched spend', value: '$4.6M', sub: '21% of file spend' },
    ],
    checks: [
      { id: 'rowcount', label: 'Row count preserved', status: 'pass', detail: '466 rows in, 466 rows out — ROC enriches 1:1.' },
      { id: 'enrich', label: 'Enrichment columns returned', status: 'pass', detail: '79 new columns added on top of the 16 submitted.' },
      { id: 'mc', label: 'Mastercard match', status: 'pass', detail: 'Mastercard status returned for 424 of 466 vendors.' },
      {
        id: 'visa',
        label: 'Visa match',
        status: 'warn',
        detail: 'Visa Matched is empty on all 466 rows for this submission.',
        action: 'Confirm with ROC whether the Visa file was run for this deal before relying on card projections.',
      },
    ],
    previews: {
      '5_ROC_pricing_export.xlsx': illumePreviews['5_ROC_pricing_export.xlsx'],
    },
  },

  'alteryx-pricing': {
    metrics: [
      { label: 'Vendors segmented', value: '466' },
      { label: 'Campaign targets', value: '457', sub: '$21.7M spend' },
      { label: 'Paid by card today', value: '243 vendors', sub: '$3.4M spend' },
    ],
    checks: [
      { id: 'rowcount', label: 'Row count preserved', status: 'pass', detail: '466 in, 466 out.' },
      { id: 'segment', label: 'Segment assigned', status: 'pass', detail: 'Every vendor carries a pricing segment label.' },
      { id: 'excl', label: 'Card rebate exclusions', status: 'pass', detail: 'Exclusion flag replaces the raw ROC suppression field.' },
      { id: 'cap', label: 'Fee cap fields', status: 'pass', detail: 'Cap Type populated on all rows.' },
    ],
    previews: {
      '6_Alteryx_PricingOutput.xlsx': illumePreviews['6_Alteryx_PricingOutput.xlsx'],
    },
  },

  classification: {
    metrics: [
      { label: 'Rules applied', value: '3' },
      { label: 'Segments overridden', value: '6' },
      { label: 'Exceptions for review', value: '0' },
    ],
    transforms: [
      { label: 'Rule 1 · Utility / energy', detail: 'Confirmed utility vendors move to Basic Match. Caught PACIFIC GAS & ELECTRIC and SOUTHERN CALIFORNIA EDISON.' },
      { label: 'Rule 2 · Government / tax authority', detail: 'Tax and water authorities move to Basic Match. Caught FRANCHISE TAX BOARD and SEMITROPIC WATER STORAGE DISTRICT.' },
      { label: 'Rule 3 · Insurance', detail: 'Insurance carriers move to Basic Match. Caught PRINCIPAL LIFE INSURANCE COMPANY.' },
      { label: 'Rule 4 · Otherwise', detail: 'Keep the Alteryx segment. If entity type is unclear, raise an exception instead of guessing.' },
    ],
    overrides: [
      { vendor: 'PACIFIC GAS & ELECTRIC', segmentBefore: 'Paymode Network Match', segmentAfter: 'Basic Match', reason: 'Utility — priced on the basic tier.' },
      { vendor: 'SOUTHERN CALIFORNIA EDISON', segmentBefore: 'Card Target - Network Match - Low', segmentAfter: 'Basic Match', reason: 'Utility — will not accept card.' },
      { vendor: 'SEMITROPIC WATER STORAGE DISTRICT', segmentBefore: 'Paymode Network Match', segmentAfter: 'Basic Match', reason: 'Public water authority.' },
      { vendor: 'FRANCHISE TAX BOARD', segmentBefore: 'Paymode Network Match', segmentAfter: 'Basic Match', reason: 'Tax authority — cannot be enrolled.' },
      { vendor: 'PRINCIPAL LIFE INSURANCE COMPANY', segmentBefore: 'Paymode Network Match', segmentAfter: 'Basic Match', reason: 'Insurance carrier.' },
      { vendor: 'VINCE DUSTERS', segmentBefore: 'Individual', segmentAfter: 'Basic Target', reason: 'Trading name, not a person — eligible to target.' },
    ],
    checks: [
      { id: 'rowcount', label: 'Row count preserved', status: 'pass', detail: '466 in, 466 out. No rows added or lost.' },
      { id: 'labels', label: 'Segment labels valid', status: 'pass', detail: 'All values exist in the segment mapping table.' },
      { id: 'spend-mix', label: 'Spend mix reasonable', status: 'pass', detail: 'Basic Match rose from 10 to 15 vendors; total spend unchanged at $21,834,520.76.' },
      { id: 'exceptions', label: 'Low-confidence rows', status: 'pass', detail: 'No vendor needed an analyst decision on this file.' },
    ],
    previews: {
      '7_Reviewed_PricingOutput_MR.xlsx': illumePreviews['7_Reviewed_PricingOutput_MR.xlsx'],
    },
  },

  'value-statement': {
    metrics: [
      { label: 'Total file spend', value: '$21.8M', sub: '3,666 transactions' },
      { label: 'Total target spend', value: '$21.7M', sub: '99.2% of file' },
      { label: 'Network matched spend', value: '$4.6M', sub: '75 vendors' },
      { label: 'Open acceptor value', value: '$547.3K' },
    ],
    checks: [
      { id: 'file-totals', label: 'File totals tie to source', status: 'pass', detail: '466 vendors / 3,666 transactions / $21,834,520.76.' },
      { id: 'split', label: 'Spend split reconciles', status: 'pass', detail: 'Check $8.93M + ACH $9.55M + Card $3.36M = $21.83M total.' },
      { id: 'formula', label: 'Formula health', status: 'pass', detail: 'No errors on Calculations, Booking Calc or the Fifth Third conversion tab.' },
      { id: 'projection', label: 'Projection sanity', status: 'pass', detail: 'No negative projections.' },
      {
        id: 'card-qa',
        label: 'Card projection depends on Visa',
        status: 'warn',
        detail: 'Visa returned no matches, so card projections lean entirely on Mastercard detail.',
        action: 'Sanity-check the card projection with the bank before it goes external.',
      },
    ],
    previews: {
      '8_Internal_Value_Statement.xlsx': illumePreviews['8_Internal_Value_Statement.xlsx'],
    },
  },

  'external-roi': {
    metrics: [
      { label: 'Slides generated', value: '19' },
      { label: 'Figures traced', value: '100%', sub: 'every number links to a cell' },
      { label: 'Program lines', value: '7', sub: 'incl. ACH migration, B2C, invoice automation' },
    ],
    checks: [
      { id: 'trace', label: 'Slide numbers trace to workbook', status: 'pass', detail: 'Every figure on the deck maps to a source cell in File 9.' },
      { id: 'internal', label: 'No internal-only fields', status: 'pass', detail: 'Internal pricing fields excluded from the external workbook and deck.' },
      { id: 'header', label: 'Header consistency', status: 'pass', detail: 'Client name, date and channel identical across workbook and deck.' },
      { id: 'brand', label: 'Brand template', status: 'pass', detail: 'Fifth Third template applied.' },
    ],
    previews: {
      '9_External_ROI_Analysis.xlsx': illumePreviews['9_External_ROI_Analysis.xlsx'],
    },
  },

  sendback: {
    metrics: [
      { label: 'Recipients', value: '3', sub: '1 to · 2 cc' },
      { label: 'Package attached', value: '2 files' },
      { label: 'Internal copy', value: 'File 8', sub: 'pricing team only' },
    ],
    checks: [
      { id: 'attach', label: 'Attachments present', status: 'pass', detail: 'External value model and ROI deck attached.' },
      { id: 'internal-split', label: 'Internal file withheld', status: 'pass', detail: 'The internal value statement is not attached to the bank-facing email.' },
      { id: 'recipients', label: 'Recipients resolved', status: 'pass', detail: 'Taken from the original analysis request thread.' },
    ],
    previews: {},
  },

  salesforce: {
    metrics: [
      { label: 'Records updated', value: '1' },
      { label: 'Opportunity', value: 'Not linked', sub: 'no SF opportunity on this deal' },
    ],
    checks: [
      { id: 'conn', label: 'Salesforce connection', status: 'pass', detail: 'Authenticated against the pricing sandbox.' },
      { id: 'fields', label: 'Required fields populated', status: 'pass', detail: 'All Calc_* pricing fields written.' },
      {
        id: 'opp',
        label: 'Opportunity link',
        status: 'warn',
        detail: 'This pricing has no Salesforce opportunity attached.',
        action: 'Ask the channel team to create or link the opportunity so the pricing can be reported on.',
      },
    ],
    previews: {
      'salesforce_sync_receipt.json': illumePreviews['salesforce_sync_receipt.json'],
    },
  },
};

export const deckSlides = illumeSlides;

export const illumeDeal: DealDefinition = {
  meta: DEAL,
  stageRuns,
  deckMap: 'illume',
  deckSlides,
};
